server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: spring-plus

  datasource:
    url: ${DB_URL:jdbc:h2:mem:spring_plus;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY:C+sUVBJ7zBgbas2UmH/NgW1yfrYQKu4ZGP9FMKfdMno=}
